// <auto-generated />
using Animals.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animals.Infrastructure.Migrations
{
    [DbContext(typeof(AnimalsContext))]
    partial class AnimalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Animals.Infrastructure.Models.AnimalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.EnclosureModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasBaseType("Animals.Infrastructure.Models.AnimalModel");

                    b.Property<bool>("CanFly")
                        .HasColumnType("INTEGER");

                    b.ToTable("Birds", (string)null);
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasBaseType("Animals.Infrastructure.Models.AnimalModel");

                    b.Property<bool>("HasFur")
                        .HasColumnType("INTEGER");

                    b.ToTable("Mammals", (string)null);
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.AnimalModel", b =>
                {
                    b.HasOne("Animals.Infrastructure.Models.EnclosureModel", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasOne("Animals.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Animals.Infrastructure.Models.BirdModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasOne("Animals.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Animals.Infrastructure.Models.MammalModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Animals.Infrastructure.Models.EnclosureModel", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
